dist: bionic
language: java
jdk:
  - openjdk11

git:
  depth: false

addons:
  sonarcloud:
    organization: "ant-media"
    token: $SONAR_TOKEN

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ffmpeg -qq -y
  - (if [ $(git ls-remote https://github.com/ant-media/ant-media-server-parent.git $TRAVIS_BRANCH  | wc -l) == "1" ];  
      then 
        echo " $TRAVIS_BRANCH branch found";  
        git clone --depth=1 -b $TRAVIS_BRANCH https://github.com/ant-media/ant-media-server-parent.git;  
      else
        echo "branch not found"; 
        git clone --depth=1 https://github.com/ant-media/ant-media-server-parent.git;  
    fi)
  - cd ant-media-server-parent
  - mvn clean install -DskipTests -Dmaven.javadoc.skip=true -Dgpg.skip=true --quiet
  - cd .. 
  
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package  org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dmaven.javadoc.skip=true --quiet
    
after_failure:
  - sudo cat hs_err_pid*.log  # cat hs_err_pid file if it exists
